// The store's contents. Edit this file to add, remove or reorder apps.
//
// kind     — which shelf it sits on: 'game', 'app' or 'toy'
// access   — how a visitor gets it, which decides the button and the "How to get it" note:
//              'play'  runs right here on lucylu.org (url is the folder under /apps/)
//              'open'  a live web app on its own site (opens in a new tab)
//              'watch' no longer available; gameplay video only
// devices  — where it works well: 'desktop', 'phone', 'ipad'
// media    — files in apps/media/: poster (jpg), video (short muted mp4 loop), shots (extra stills),
//            youtube (id of a full video, played in the details sheet), phone (captured at phone size)
// hue      — icon colour when there's no icon image: a pair of CSS colours
// note     — a one-line heads-up shown under the button (slow first load, needs an account, ...)
window.CATALOG = {
  featured: ['stockwave', 'starbreaker', 'world-sense', 'glow'],
  apps: [
    // ── Games ───────────────────────────────────────────────
    { id: 'stockwave', name: 'Stockwave', subtitle: 'Paper trading, fast-forwarded', kind: 'game',
      access: 'open', url: 'https://www.playstockwave.com/', devices: ['desktop', 'phone'],
      media: { poster: 'stockwave.jpg', video: 'stockwave.mp4' }, icon: 'icons/stockwave.png', hue: ['#1f6b5c', '#58c49a'],
      note: 'Runs on a free server: the first visit can take half a minute to wake up.',
      body: 'Trade real market data in a fast-replay paper trading game. You start with $1M of virtual cash and watch months of the market go by in minutes.',
      made: 'React, Node, live market data', year: 2026 },
    { id: 'starbreaker', name: 'Starbreaker', subtitle: "Swipe n' chill puzzles in space", kind: 'game',
      access: 'watch', devices: ['ipad'], status: 'Retired from the App Store',
      media: { poster: 'starbreaker.jpg', video: 'starbreaker.mp4', shots: ['starbreaker-2.jpg', 'starbreaker-3.jpg'], youtube: 'ELOKL_uuzIE' },
      hue: ['#2a2f7a', '#f2a93b'],
      body: 'A match puzzle with an astronaut cat. Hop between levels on a map around the moon, clear jelly and blockers in a set number of moves, and pick up boosters on the way.',
      made: 'Unity, for iPhone and iPad · Paperbox Studio', year: 2023 },
    { id: 'lunescape', name: 'Lunescape', subtitle: 'Isometric farming and survival', kind: 'game',
      access: 'watch', devices: ['ipad'], status: 'Retired from the App Store',
      media: { poster: 'lunescape.jpg', youtube: '8Jjn_P_nJzQ' }, hue: ['#b8653a', '#f2c28a'],
      body: 'Keep a homestead going in a sunbaked low-poly world: plant and water crops, keep the animals fed, craft tools, and watch your health and energy as the days pass.',
      made: 'Unity, for iPad · Paperbox Studio', year: 2022 },
    { id: 'daily-transmission', name: 'Daily Transmission', subtitle: 'A Morse code puzzle a day', kind: 'game',
      access: 'play', url: 'daily-transmission/', devices: ['phone', 'desktop'],
      media: { poster: 'daily-transmission.jpg', video: 'daily-transmission.mp4', phone: true }, hue: ['#16324a', '#e0b65a'],
      body: 'Decode the day’s phrase from Morse code and keep your streak alive. One new transmission every day.',
      made: 'React', year: 2026 },
    { id: 'math-gym', name: 'Math Gym', subtitle: 'Mental math workouts', kind: 'game',
      access: 'watch', devices: ['ipad'], status: 'Retired from the App Store', media: {}, hue: ['#3b4a8a', '#8fb2ff'],
      body: 'Short mental arithmetic workouts for iPhone and iPad. No longer listed, and there is no footage of it here yet.',
      made: 'Paperbox Studio', year: 2023 },

    // ── Apps ────────────────────────────────────────────────
    { id: 'world-sense', name: 'Earth’s Sensorium', subtitle: 'How the planet perceives itself', kind: 'app',
      access: 'open', url: 'https://world-sense-eight.vercel.app/', devices: ['desktop', 'phone'],
      media: { poster: 'world-sense.jpg', video: 'world-sense.mp4' }, icon: 'icons/world-sense.png', hue: ['#2c4a3e', '#c9b27a'],
      body: '124 instruments through which the planet senses the world, from seismometers to sea-floor microphones, arranged as senses rather than scientific disciplines.',
      made: 'Static site', year: 2026 },
    { id: 'cohear', name: 'Cohear', subtitle: 'Listen together, be there anywhere', kind: 'app',
      access: 'open', url: 'https://cohere-main.netlify.app/', devices: ['desktop', 'phone'],
      media: { poster: 'cohear.jpg', video: 'cohear.mp4' }, icon: 'icons/cohear.png', hue: ['#4a2a6a', '#e07ab8'],
      body: 'Concert discovery with synchronized live rooms, so you can follow a show in sync with the crowd from wherever you are.',
      made: 'React, Vite', year: 2026 },
    { id: 'totd', name: 'Thing of the Day', subtitle: 'A daily dose of the interesting', kind: 'app',
      access: 'open', url: 'https://totd.vercel.app/', devices: ['desktop', 'phone'],
      media: { poster: 'totd.jpg', video: 'totd.mp4' }, icon: 'icons/totd.png', hue: ['#1b1b1b', '#e8a35a'],
      body: 'A generated daily edition: one thing a day, with pictures and notes. Step back through past editions or jump around the calendar.',
      made: 'Next.js', year: 2026 },
    { id: 'booklit', name: 'Booklit', subtitle: 'Reading tracker and 3D shelf', kind: 'app',
      access: 'open', url: 'https://bookreader-af115.web.app/', devices: ['desktop'],
      media: { poster: 'booklit.jpg', video: 'booklit.mp4' }, icon: 'icons/booklit.png', hue: ['#5a3a22', '#e3b77a'],
      note: 'It opens with a sign-in box; choose “Continue as Guest” to look around.',
      body: 'A Goodreads-backed reading tracker with a local book library and a 3D shelf, and a read-aloud ebook reader.',
      made: 'React, Firebase', year: 2026 },
    { id: 'final-drafter', name: 'Final Drafter', subtitle: 'Screenplay editor', kind: 'app',
      access: 'open', url: 'https://final-drafter.vercel.app/', devices: ['desktop'],
      media: { poster: 'final-drafter.jpg', video: 'final-drafter.mp4' }, icon: 'icons/final-drafter.png', hue: ['#2a2a2a', '#d9d4c7'],
      body: 'Write and format screenplays in the browser. Scene headings, action and dialogue fall into place as you type, and projects save as .fdproj files.',
      made: 'React', year: 2026 },
    { id: 'breathe', name: 'Breathe', subtitle: 'Breath-hold tracker', kind: 'app',
      access: 'open', url: 'https://breathcount.netlify.app/', devices: ['phone', 'desktop'],
      media: { poster: 'breathe.jpg', video: 'breathe.mp4', phone: true }, icon: 'icons/breathe.png', hue: ['#3d6b63', '#a8d8c8'],
      body: 'A quiet practice for timing and tracking breath holds.',
      made: 'Static site', year: 2026 },
    { id: 'drops', name: 'Drops', subtitle: 'Language flashcards', kind: 'app',
      access: 'play', url: 'drops/', devices: ['phone', 'desktop'],
      media: { poster: 'drops.jpg', video: 'drops.mp4', phone: true }, hue: ['#1d5a8a', '#7cc8f0'],
      body: 'Multi-deck language flashcards with difficulty modes, read-aloud and live XP.',
      made: 'React', year: 2026 },
    { id: 'paper-sim', name: 'Paper Sim', subtitle: 'Fold paper and boxes in 3D', kind: 'app',
      access: 'play', url: 'paper-sim/', devices: ['desktop'],
      media: { poster: 'paper-sim.jpg' }, hue: ['#b8884a', '#f0d9a8'],
      note: 'Projects are saved in this browser.',
      body: 'A cozy sandbox for origami and packaging. Design a flat dieline, fold it step by step in 3D with a hinge gizmo, then print it at true scale or export the instructions.',
      made: 'TypeScript, React, three.js', year: 2026 },
    { id: 'periodic-table', name: '3D Periodic Table', subtitle: 'The elements, in space', kind: 'app',
      access: 'open', url: 'https://www.lulucy.org/3d-table', devices: ['desktop'],
      media: { poster: 'periodic-table.jpg', video: 'periodic-table.mp4' }, hue: ['#13233a', '#6ad1e3'],
      body: 'The periodic table as a 3D object you can turn and explore.',
      made: 'Three.js', year: 2024 },
    { id: 'neuralens', name: 'Neuralens', subtitle: 'Checkout in one snap', kind: 'app',
      access: 'play', url: 'neuralens/', devices: ['desktop', 'phone'],
      media: { poster: 'neuralens.jpg', video: 'neuralens.mp4' }, icon: 'icons/neuralens.png', hue: ['#1f2d4a', '#9a7cff'],
      body: 'A computer-vision checkout: take one photo of the basket and it rings up every item. This is the project page, with the iOS demo apps.',
      made: 'Computer vision', year: 2023 },

    // ── Toys & experiments (all hosted here) ───────────────
    { id: 'glow', name: 'Glow', subtitle: 'Liquid gradient UI', kind: 'toy', access: 'play', url: 'glow/', devices: ['desktop'],
      media: { poster: 'glow.jpg', video: 'glow.mp4' }, hue: ['#7a2a8a', '#ff8a5c'],
      body: 'A set of widgets (health stats, a focus timer, a music player) made of slow liquid gradients and film grain.', made: 'Three.js', year: 2026 },
    { id: 'inductive-bloom', name: 'Inductive Bloom', subtitle: 'Generative flowers', kind: 'toy', access: 'play', url: 'inductive-bloom/', devices: ['desktop'],
      media: { poster: 'inductive-bloom.jpg', video: 'inductive-bloom.mp4' }, hue: ['#8a3858', '#f2b5c8'],
      body: 'A generative bloom that grows itself, built with p5.js.', made: 'p5.js', year: 2026 },
    { id: 'meridian-atlas', name: 'The Meridian Atlas', subtitle: 'Vesalian edition', kind: 'toy', access: 'play', url: 'meridian-atlas/', devices: ['desktop'],
      media: { poster: 'meridian-atlas.jpg', video: 'meridian-atlas.mp4' }, hue: ['#6a4a2a', '#e6d2a8'],
      body: 'The body’s meridians drawn as an interactive anatomical atlas, in the manner of an old engraved plate.', made: 'React, Framer Motion', year: 2026 },
    { id: 'archive-studio', name: 'Archive Deck Studio', subtitle: 'Archive cards from a prompt', kind: 'toy', access: 'play', url: 'archive-studio/', devices: ['desktop'],
      media: { poster: 'archive-studio.jpg', video: 'archive-studio.mp4' }, hue: ['#3a3326', '#cbb88a'],
      body: 'Type a prompt and get an archive-style deck of cards in procedural ink on an infinite canvas, ready to export.', made: 'Tailwind, JSZip', year: 2026 },
    { id: 'js-piano', name: 'JS Piano', subtitle: 'A playable piano', kind: 'toy', access: 'play', url: 'js-piano/', devices: ['desktop'],
      media: { poster: 'js-piano.jpg', video: 'js-piano.mp4' }, hue: ['#1a1a1a', '#f0ece2'],
      body: 'Play with the mouse or your keyboard.', made: 'Plain JavaScript', year: 2026 },
    { id: 'js-piano-batch', name: 'JS Piano 8b', subtitle: 'Piano with song import', kind: 'toy', access: 'play', url: 'js-piano-batch/', devices: ['desktop'],
      media: { poster: 'js-piano-batch.jpg' }, hue: ['#2a1a3a', '#c8a8ff'],
      body: 'The piano, plus batch import of 8-bit songs to play back.', made: 'Plain JavaScript', year: 2026 },
    { id: 'cosmic-clock', name: 'Cosmic Age Clock', subtitle: 'Now, against the age of the universe', kind: 'toy', access: 'play', url: 'cosmic-clock/', devices: ['desktop', 'phone'],
      media: { poster: 'cosmic-clock.jpg', video: 'cosmic-clock.mp4' }, hue: ['#0e1430', '#7a8cff'],
      body: 'A rotating clock that places the current moment on cosmological timescales.', made: 'Canvas', year: 2026 },
    { id: 'apple-watch', name: 'Infinite Canvas Watch', subtitle: 'An analog face on an endless canvas', kind: 'toy', access: 'play', url: 'apple-watch/', devices: ['desktop', 'phone'],
      media: { poster: 'apple-watch.jpg', video: 'apple-watch.mp4' }, hue: ['#111111', '#ff9f43'],
      body: 'A watch face with a live analog clock, floating on an infinite canvas.', made: 'Canvas', year: 2026 },
    { id: 'zodiac-watch', name: 'Zodiac Watch', subtitle: 'Twelve animals, one face', kind: 'toy', access: 'play', url: 'zodiac-watch/', devices: ['desktop'],
      media: { poster: 'zodiac-watch.jpg', video: 'zodiac-watch.mp4' }, hue: ['#3a1a14', '#e6b85c'],
      body: 'A watch face that pairs the twelve animal signs with the time.', made: 'Canvas', year: 2026 },
    { id: 'zodiac-wheel', name: 'Zodiac Wheel', subtitle: 'The twelve animals', kind: 'toy', access: 'play', url: 'zodiac-wheel/', devices: ['phone'],
      media: { poster: 'zodiac-wheel.jpg', video: 'zodiac-wheel.mp4', phone: true }, hue: ['#4a1a1a', '#f0c27a'],
      body: 'A phone-sized wheel of the twelve animal signs.', made: 'Canvas', year: 2026 },
  ],
};
