// The store's contents. Edit this file to add, remove or reorder apps.
//
// kind     — which shelf it sits on: 'game', 'app' or 'toy'
// access   — how a visitor gets it, which decides the button and the "How to get it" note:
//              'play'  runs right here on lucylu.org (url is the folder under /apps/)
//              'open'  a live web app on its own site (opens in a new tab)
//              'watch' no longer available; gameplay video only
// devices  — where it works well: 'desktop', 'phone', 'ipad'
// media    — files in apps/media/: poster (jpg), video (short muted mp4 loop), shots (extra stills),
//            fit (4:3 captures: show the whole frame over a blurred copy), youtube (id of a full video, played in the details sheet), phone (captured at phone size)
// hue      — icon colour when there's no icon image: a pair of CSS colours
// note     — a one-line heads-up shown under the button (slow first load, needs an account, ...)
window.CATALOG = {
  featured: ['snark-weather', 'breathe', 'starbreaker', 'world-sense'],
  apps: [
    // ── Games ───────────────────────────────────────────────
    { id: 'jelly-toss', name: 'Jelly Toss', subtitle: 'A very small world with excellent bounce', kind: 'game',
      access: 'open', url: 'https://jelly.scottsun.io', devices: ['desktop', 'phone'],
      media: { poster: 'jelly-toss.jpg', video: 'jelly-toss.mp4' }, hue: ['#c2457a', '#ffb3c9'],
      body: 'Wander a 7 cm jelly around a warm wooden tabletop. Try the swing and the trampoline, pull it by the crown and let go, and watch the wobble travel through it.',
      made: 'Three.js, TypeScript · with Scott Sun', year: 2026 },
    { id: 'stockwave', name: 'Stockwave', subtitle: 'Paper trading, fast-forwarded', kind: 'game',
      access: 'open', url: 'https://www.playstockwave.com/', devices: ['desktop', 'phone'],
      media: { poster: 'stockwave.jpg', video: 'stockwave.mp4' }, icon: 'icons/stockwave.png', hue: ['#1f6b5c', '#58c49a'],
      note: 'Runs on a free server: the first visit can take half a minute to wake up.',
      body: 'Trade real market data in a fast-replay paper trading game. You start with $1M of virtual cash and watch months of the market go by in minutes.',
      made: 'React, Node, live market data', year: 2026 },
    { id: 'starbreaker', name: 'Starbreaker', subtitle: "Swipe n' chill puzzles in space", kind: 'game',
      access: 'watch', devices: ['ipad'], status: 'Retired from the App Store',
      media: { poster: 'starbreaker.jpg', video: 'starbreaker.mp4', fit: true, shots: ['starbreaker-2.jpg', 'starbreaker-3.jpg'], youtube: 'ELOKL_uuzIE' },
      hue: ['#2a2f7a', '#f2a93b'],
      body: 'A match puzzle with an astronaut cat. Hop between levels on a map around the moon, clear jelly and blockers in a set number of moves, and pick up boosters on the way.',
      made: 'Unity, for iPhone and iPad · Paperbox Studio', year: 2023 },
    { id: 'lunescape', name: 'Lunescape', subtitle: 'Isometric farming and survival', kind: 'game',
      access: 'watch', devices: ['ipad'], status: 'Retired from the App Store',
      media: { poster: 'lunescape.jpg', youtube: '8Jjn_P_nJzQ' }, hue: ['#b8653a', '#f2c28a'],
      body: 'Keep a homestead going in a sunbaked low-poly world: plant and water crops, keep the animals fed, craft tools, and watch your health and energy as the days pass.',
      made: 'Unity, for iPad · Paperbox Studio', year: 2022 },
    { id: 'daily-transmission', name: 'Daily Transmission', subtitle: 'A Morse code puzzle a day', kind: 'game',
      access: 'play', url: 'daily-transmission/', devices: ['phone', 'desktop'],
      media: { poster: 'daily-transmission.jpg', video: 'daily-transmission.mp4', phone: true, shots: ['daily-transmission-shot-2.jpg', 'daily-transmission-shot-3.jpg', 'daily-transmission-shot-4.jpg', 'daily-transmission-shot-5.jpg'] }, hue: ['#16324a', '#e0b65a'],
      body: 'Decode the day’s phrase from Morse code and keep your streak alive. One new transmission every day.',
      made: 'React', year: 2026 },
    { id: 'memory-towers', name: 'Memory Towers', subtitle: 'Left or right, all the way up', kind: 'game',
      access: 'play', url: 'memory-towers/', devices: ['phone', 'desktop'],
      media: { poster: 'memory-towers.jpg', phone: true, shots: ['memory-towers-shot-2.jpg', 'memory-towers-shot-3.jpg', 'memory-towers-shot-4.jpg'] }, hue: ['#3341c9', '#f59e0b'],
      body: 'Every floor has two doors and only one of them goes up. Pick the wrong one and you are back on floor 1, so remember the way. The tower changes every day.',
      made: 'React', year: 2026 },
    { id: 'cereal', name: 'Milk & Letters', subtitle: 'A cozy word game in a bowl of cereal', kind: 'game',
      access: 'play', url: 'cereal/', devices: ['desktop', 'phone'],
      media: { poster: 'cereal.jpg', video: 'cereal.mp4' }, hue: ['#e9a56b', '#fbf5e8'],
      body: 'Letters float in a bowl of milk. Spoon up the ones you want, build the best word you can, and beat the clock before the milk gets cold. There is a new bowl every day.',
      made: 'three.js, JavaScript', year: 2026 },
    { id: 'math-gym', name: 'Math Gym', subtitle: 'Mental math workouts', kind: 'game',
      access: 'watch', devices: ['ipad'], status: 'Retired from the App Store', media: {}, hue: ['#3b4a8a', '#8fb2ff'],
      body: 'Short mental arithmetic workouts for iPhone and iPad. No longer listed, and there is no footage of it here yet.',
      made: 'Paperbox Studio', year: 2023 },

    // ── Apps ────────────────────────────────────────────────
    { id: 'chrome-home', name: 'Chrome Home', subtitle: 'Calm new-tab focus dashboard', kind: 'app',
      access: 'play', url: 'chrome-home/', devices: ['desktop'],
      media: { poster: 'chrome-home.jpg', video: 'chrome-home.mp4' }, icon: 'icons/chrome-home.png', hue: ['#e8b860', '#f4e4b8'],
      note: 'Runs directly in your browser. Also installable as an unpacked Chrome extension.',
      body: 'A calm focus dashboard with a flip clock over a liquid gradient background, daily focus prompt, to-do list drawer, weather, and custom shortcuts.',
      made: 'Manifest V3, Three.js, Canvas, JavaScript', year: 2026 },
    { id: 'gallery-downloader', name: 'Gallery Downloader', subtitle: 'High-res image extractor & ZIP archiver', kind: 'app',
      access: 'play', url: 'gallery-downloader/', devices: ['desktop'],
      media: { poster: 'gallery-downloader.jpg', video: 'gallery-downloader.mp4', fit: true }, icon: 'icons/gallery-downloader.png', hue: ['#1a2a78', '#4080e8'],
      note: 'Demo mode scans sample galleries. Install the Chrome extension to extract images from any tab.',
      body: 'Scans web pages for photography and assets, bypasses thumbnails to grab full-resolution sources, hides website chrome and tracker beacons, and bundles images into one-click ZIP downloads.',
      made: 'Manifest V3, Chrome Side Panel, JavaScript', year: 2026 },
    { id: 'session-keeper', name: 'Session Keeper', subtitle: 'Tab session manager & export dashboard', kind: 'app',
      access: 'play', url: 'session-keeper/', devices: ['desktop'],
      media: { poster: 'session-keeper.jpg', video: 'session-keeper.mp4' }, icon: 'icons/session-keeper.png', hue: ['#1e3a5f', '#64b5f6'],
      note: 'Demo mode lets you explore sessions and export. Install the extension for automatic tab backups.',
      body: 'A clean session manager for autosaving browser windows, naming custom workspaces, restoring tabs, and exporting tab sessions as Markdown or plain text code blocks.',
      made: 'Manifest V3, IndexedDB, JavaScript', year: 2026 },
    { id: 'codepen-library-saver', name: 'CodePen Saver', subtitle: 'Offline CodePen cataloger & archiver', kind: 'app',
      access: 'open', url: 'https://github.com/lucyellu/chrome-extensions', devices: ['desktop'],
      media: { poster: 'codepen-library-saver.jpg', video: 'codepen-library-saver.mp4', fit: true }, icon: 'icons/codepen-library-saver.png', hue: ['#24292e', '#ff3c41'],
      body: 'A side-panel extension to capture, tag, catalog, and export CodePens into standalone offline HTML files with tags and fallback source capture.',
      made: 'Manifest V3, Vite, TypeScript', year: 2026 },
    { id: 'speed-read', name: 'Speed Read', subtitle: 'On-device Gemini Nano article summarizer', kind: 'app',
      access: 'open', url: 'https://github.com/lucyellu/chrome-extensions', devices: ['desktop'],
      media: { poster: 'speed-read.jpg', fit: true }, icon: 'icons/speed-read.png', hue: ['#3a1868', '#7a48b8'],
      body: 'Instant multi-register article summarizer powered by Chrome\'s built-in on-device Gemini Nano model. Compresses any article into ELI5, Elevator Pitch, and Postdoc Abstract without sending data off your machine.',
      made: 'Manifest V3, Chrome Prompt API (Gemini Nano)', year: 2026 },
    { id: 'ad-filter', name: 'Ad Filter', subtitle: 'Quiet browsing with local review triage', kind: 'app',
      access: 'open', url: 'https://github.com/lucyellu/chrome-extensions', devices: ['desktop'],
      media: { poster: 'ad-filter.jpg', video: 'ad-filter.mp4' }, icon: 'icons/ad-filter.png', hue: ['#1a5848', '#60c0a0'],
      body: 'A Manifest V3 ad-blocking prototype that logs blocked trackers and cosmetic DOM ads locally to IndexedDB, letting you review them later with a neutral Yes/No decision and optional AI triage.',
      made: 'Manifest V3, DeclarativeNetRequest, IndexedDB', year: 2026 },
    { id: 'cohear', name: 'Cohear', subtitle: 'Listen together, be there anywhere', kind: 'app',
      access: 'open', url: 'https://cohere-main.netlify.app/', devices: ['desktop', 'phone'],
      media: { poster: 'cohear.jpg', video: 'cohear.mp4' }, icon: 'icons/cohear.png', hue: ['#4a2a6a', '#e07ab8'],
      body: 'Concert discovery with synchronized live rooms, so you can follow a show in sync with the crowd from wherever you are.',
      made: 'React, Vite', year: 2026 },
    { id: 'booklit', name: 'Booklit', subtitle: 'Reading tracker and 3D shelf', kind: 'app',
      access: 'open', url: 'https://bookreader-af115.web.app/', devices: ['desktop'],
      media: { poster: 'booklit.jpg', video: 'booklit.mp4' }, icon: 'icons/booklit.png', hue: ['#5a3a22', '#e3b77a'],
      note: 'It opens with a sign-in box; choose “Continue as Guest” to look around.',
      body: 'A Goodreads-backed reading tracker with a local book library and a 3D shelf, and a read-aloud ebook reader.',
      made: 'React, Firebase', year: 2026 },
    { id: 'final-drafter', name: 'Final Drafter', subtitle: 'Screenplay editor', kind: 'app',
      access: 'open', url: 'https://final-drafter.vercel.app/', devices: ['desktop'],
      media: { poster: 'final-drafter.jpg', video: 'final-drafter.mp4' }, icon: 'icons/final-drafter.png', hue: ['#2a2a2a', '#d9d4c7'],
      body: 'Write and format screenplays in the browser. Scene headings, action and dialogue fall into place as you type, and projects save as .fdproj files.',
      made: 'React', year: 2026 },
    { id: 'breathe', name: 'Breathe', subtitle: 'Breath-hold tracker', kind: 'app',
      access: 'open', url: 'https://breathcount.netlify.app/', devices: ['phone', 'desktop'],
      media: { poster: 'breathe.jpg', video: 'breathe.mp4', phone: true, shots: ['breathe-2.jpg'] }, icon: 'icons/breathe.png', hue: ['#3d6b63', '#a8d8c8'],
      body: 'A quiet practice for timing and tracking breath holds.',
      made: 'Static site', year: 2026 },
    { id: 'snark-weather', name: 'Snark Weather', subtitle: 'A forecast with attitude', kind: 'app',
      access: 'open', url: 'https://snark-weather.vercel.app/', devices: ['phone', 'desktop'],
      media: { poster: 'snark-weather.jpg', video: 'snark-weather.mp4', phone: true, shots: ['snark-weather-2.jpg', 'snark-weather-3.jpg'] },
      icon: 'icons/snark-weather.png', hue: ['#cd3222', '#f3c9c0'],
      body: 'A glass-cloud weather app that tells you the forecast in one dry sentence, and remembers whose birthday it is. Hourly and 7-day views, a month calendar with the weather on every day, and six colour themes.',
      made: 'React, TypeScript, Open-Meteo', year: 2026 },
    { id: 'drops', name: 'Drops', subtitle: 'Language flashcards', kind: 'app',
      access: 'play', url: 'drops/', devices: ['phone', 'desktop'],
      media: { poster: 'drops.jpg', video: 'drops.mp4', phone: true, shots: ['drops-shot-2.jpg', 'drops-shot-3.jpg', 'drops-shot-4.jpg', 'drops-shot-5.jpg'] }, hue: ['#1d5a8a', '#7cc8f0'],
      body: 'Multi-deck language flashcards with difficulty modes, read-aloud and live XP.',
      made: 'React', year: 2026 },
    { id: 'paper-sim', name: 'Paper Sim', subtitle: 'Fold paper and boxes in 3D', kind: 'app',
      access: 'play', url: 'paper-sim/', devices: ['desktop'],
      media: { poster: 'paper-sim.jpg', video: 'paper-sim.mp4' }, hue: ['#b8884a', '#f0d9a8'],
      note: 'Projects are saved in this browser.',
      body: 'A cozy sandbox for origami and packaging. Design a flat dieline, fold it step by step in 3D with a hinge gizmo, then print it at true scale or export the instructions.',
      made: 'TypeScript, React, three.js', year: 2026 },
    { id: 'atlas-library', name: 'Atlas Library', subtitle: 'Scale, mass and temperature of everything', kind: 'app',
      access: 'play', url: 'atlas-library/', devices: ['desktop'],
      media: { poster: 'atlas-library.jpg', video: 'atlas-library.mp4' }, hue: ['#3b4a46', '#b9c8c0'],
      body: 'Three interactive atlases of the universe. Zoom from the Planck length to the observable universe, weigh everything from an electron to a galaxy, and run from absolute zero to the hottest thing there is.',
      made: 'JavaScript, SVG', year: 2026 },
    { id: 'periodic-table', name: '3D Periodic Table', subtitle: 'The elements, in space', kind: 'app',
      access: 'open', url: 'https://www.lulucy.org/3d-table', devices: ['desktop'],
      media: { poster: 'periodic-table.jpg', video: 'periodic-table.mp4' }, hue: ['#13233a', '#6ad1e3'],
      body: 'The periodic table as a 3D object you can turn and explore.',
      made: 'Three.js', year: 2024 },
    { id: 'neuralens', name: 'Neuralens', subtitle: 'Checkout in one snap', kind: 'app',
      access: 'play', url: 'neuralens/', devices: ['desktop', 'phone'],
      media: { poster: 'neuralens.jpg', video: 'neuralens.mp4' }, icon: 'icons/neuralens.png', hue: ['#1f2d4a', '#9a7cff'],
      body: 'A computer-vision checkout: take one photo of the basket and it rings up every item. This is the project page, with the iOS demo apps.',
      made: 'Computer vision', year: 2023 },

    // ── Toys & experiments (all hosted here) ───────────────
    { id: 'glow', name: 'Glow', subtitle: 'Liquid gradient UI', kind: 'toy', access: 'play', url: 'glow/', devices: ['desktop'],
      media: { poster: 'glow.jpg', video: 'glow.mp4' }, hue: ['#7a2a8a', '#ff8a5c'],
      body: 'A set of widgets (health stats, a focus timer, a music player) made of slow liquid gradients and film grain.', made: 'Three.js', year: 2026 },
    { id: 'inductive-bloom', name: 'Inductive Bloom', subtitle: 'Generative flowers', kind: 'toy', access: 'play', url: 'inductive-bloom/', devices: ['desktop'],
      media: { poster: 'inductive-bloom.jpg', video: 'inductive-bloom.mp4' }, hue: ['#8a3858', '#f2b5c8'],
      body: 'A generative bloom that grows itself, built with p5.js.', made: 'p5.js', year: 2026 },
    { id: 'meridian-atlas', name: 'The Meridian Atlas', subtitle: 'Vesalian edition', kind: 'toy', access: 'play', url: 'meridian-atlas/', devices: ['desktop'],
      media: { poster: 'meridian-atlas.jpg', video: 'meridian-atlas.mp4' }, hue: ['#6a4a2a', '#e6d2a8'],
      body: 'The body’s meridians drawn as an interactive anatomical atlas, in the manner of an old engraved plate.', made: 'React, Framer Motion', year: 2026 },
    { id: 'archive-studio', name: 'Archive Deck Studio', subtitle: 'Archive cards from a prompt', kind: 'toy', access: 'play', url: 'archive-studio/', devices: ['desktop'],
      media: { poster: 'archive-studio.jpg', video: 'archive-studio.mp4' }, hue: ['#3a3326', '#cbb88a'],
      body: 'Type a prompt and get an archive-style deck of cards in procedural ink on an infinite canvas, ready to export.', made: 'Tailwind, JSZip', year: 2026 },
    { id: 'wiki-times', name: 'The Wiki Times', subtitle: 'Wikipedia at your reading level', kind: 'app', access: 'play', url: 'wiki-times/', devices: ['desktop', 'phone'],
      media: {}, hue: ['#1f3a34', '#e8d9b0'],
      note: 'Free mode swaps in easier words. Paste your own AI key in Settings for full rewrites and Voices (greentext, ELI5, postdoc and more); the key stays in your browser.',
      body: 'Open any Wikipedia article or web page and slide it from kindergarten to 8th grade, or switch to a Voice. Hard words you are meant to learn are underlined and save as flashcards.', made: 'Plain JavaScript, word-frequency data, optional bring-your-own AI key', year: 2026 },
    { id: 'noteforge', name: 'NoteForge Piano', subtitle: 'Audio to piano roll, sheet and chords', kind: 'app', access: 'play', url: 'noteforge/', devices: ['desktop'],
      media: { poster: 'noteforge.jpg', video: 'noteforge.mp4' }, hue: ['#0a2a4a', '#4aa8ff'],
      note: 'Runs entirely in your browser; your audio is never uploaded.',
      body: 'Drop in a song and watch it turn into a falling-note piano roll, sheet music and chords, with playback, WAV and MIDI export.', made: 'Plain JavaScript, Web Audio', year: 2026 },
    { id: 'myspot', name: 'My Spot', subtitle: 'A player for a very big music library', kind: 'app',
      access: 'open', url: 'https://myspot-web.netlify.app/', devices: ['desktop'],
      media: { poster: 'myspot.jpg', video: 'myspot.mp4' }, hue: ['#4a5a1f', '#c8e04a'],
      body: 'A YouTube-style player for thousands of AI-made songs, with synced lyrics, channels and playlists, and a side panel for making cover art and visuals to play along with each track.',
      made: 'Python, FastAPI, JavaScript', year: 2026 },
    { id: 'world-sense', name: 'Earth’s Sensorium', subtitle: 'How the planet perceives itself', kind: 'app',
      access: 'open', url: 'https://world-sense-eight.vercel.app/', devices: ['desktop', 'phone'],
      media: { poster: 'world-sense.jpg', video: 'world-sense.mp4' }, icon: 'icons/world-sense.png', hue: ['#2c4a3e', '#c9b27a'],
      body: '124 instruments through which the planet senses the world, from seismometers to sea-floor microphones, arranged as senses rather than scientific disciplines.',
      made: 'Static site', year: 2026 },
    { id: 'js-piano', name: 'JS Piano', subtitle: 'A playable piano', kind: 'toy', access: 'play', url: 'js-piano/', devices: ['desktop'],
      media: { poster: 'js-piano.jpg', video: 'js-piano.mp4' }, hue: ['#1a1a1a', '#f0ece2'],
      body: 'Play with the mouse or your keyboard.', made: 'Plain JavaScript', year: 2026 },
    { id: 'js-piano-batch', name: 'JS Piano 8b', subtitle: 'Piano with song import', kind: 'toy', access: 'play', url: 'js-piano-batch/', devices: ['desktop'],
      media: { poster: 'js-piano-batch.jpg' }, hue: ['#2a1a3a', '#c8a8ff'],
      body: 'The piano, plus batch import of 8-bit songs to play back.', made: 'Plain JavaScript', year: 2026 },
    { id: 'cosmic-clock', name: 'Cosmic Age Clock', subtitle: 'Now, against the age of the universe', kind: 'toy', access: 'play', url: 'cosmic-clock/', devices: ['desktop', 'phone'],
      media: { poster: 'cosmic-clock.jpg', video: 'cosmic-clock.mp4' }, hue: ['#0e1430', '#7a8cff'],
      body: 'A rotating clock that places the current moment on cosmological timescales.', made: 'Canvas', year: 2026 },
    { id: 'apple-watch', name: 'Infinite Canvas Watch', subtitle: 'An analog face on an endless canvas', kind: 'toy', access: 'play', url: 'apple-watch/', devices: ['desktop', 'phone'],
      media: { poster: 'apple-watch.jpg', video: 'apple-watch.mp4' }, hue: ['#111111', '#ff9f43'],
      body: 'A watch face with a live analog clock, floating on an infinite canvas.', made: 'Canvas', year: 2026 },
    { id: 'zodiac-watch', name: 'Zodiac Watch', subtitle: 'Twelve animals, one face', kind: 'toy', access: 'play', url: 'zodiac-watch/', devices: ['desktop'],
      media: { poster: 'zodiac-watch.jpg', video: 'zodiac-watch.mp4', shots: ['zodiac-watch-shot-2.jpg', 'zodiac-watch-shot-3.jpg', 'zodiac-watch-shot-4.jpg'] }, hue: ['#3a1a14', '#e6b85c'],
      body: 'A watch face that pairs the twelve animal signs with the time.', made: 'Canvas', year: 2026 },
    { id: 'zodiac-wheel', name: 'Zodiac Wheel', subtitle: 'The twelve animals', kind: 'toy', access: 'play', url: 'zodiac-wheel/', devices: ['phone'],
      media: { poster: 'zodiac-wheel.jpg', video: 'zodiac-wheel.mp4', phone: true, shots: ['zodiac-wheel-shot-2.jpg', 'zodiac-wheel-shot-3.jpg', 'zodiac-wheel-shot-4.jpg'] }, hue: ['#4a1a1a', '#f0c27a'],
      body: 'A phone-sized wheel of the twelve animal signs.', made: 'Canvas', year: 2026 },
  ],
};
